-- Hisaab — Audit 2026-09 item C10 (kameti part): make "provably fair" binding.
--
-- Apply in Supabase Studio AFTER supabase-migration-committees.sql and
-- supabase-migration-committees-phase2.sql. Idempotent: safe to re-run.
--
-- ── Evidence ────────────────────────────────────────────────────────────────
--
-- docs/audit-2026-09/05-security.md M10 — "Kameti 'provably fair' ballot is not
--   a real commit-reveal — the organiser can re-roll until the draw suits them".
--   src/stores/committeeStore.ts:115-130 generated the seed, the commitment AND
--   the slot order on the organiser's own device and wrote them in one plain
--   UPDATE. supabase-migration-committees.sql:55-73 gives the organiser a plain
--   owner UPDATE policy, so the DB accepted any (seed, commitment, order)
--   triple — even a mutually inconsistent one. phase2.sql:18-57 then served
--   those stored values verbatim to anon via get_committee_witness() as "the
--   honest record".
--   The attack needs no tooling: re-run the local draw until slot 1 is yours,
--   then persist the matching pair. Every witness verification passes. Worse,
--   because the order is a deterministic function of the seed, brute-forcing a
--   seed that produces ANY chosen permutation of N members costs ~N! hashes —
--   about 3.6M for N=10, i.e. a second of client CPU.
--
-- docs/audit-2026-09/12-qa-review.md F-13 — "Ballot re-run possible (no
--   store/server drawn-guard)"; the manual QA sheet (line 307) already expects
--   "double-tap the draw button — slots must not silently re-shuffle
--   (F-13, expected fragile)".
--
-- ── What this migration does ────────────────────────────────────────────────
--
-- 1. perform_committee_draw(p_committee_id) — a SECURITY DEFINER RPC that, in
--    ONE transaction: locks the committee row, checks the caller is the
--    organiser, refuses if a draw already exists (stable code ALREADY_DRAWN),
--    generates the seed from SERVER entropy (gen_random_bytes), computes the
--    order in SQL, writes every member slot + the committee draw columns, and
--    returns the order. The organiser never supplies or sees the seed before
--    it is committed, so there is nothing left to re-roll.
--
-- 2. Two BEFORE INSERT/UPDATE triggers that make the draw append-only against
--    RAW PostgREST writes, not just against the app:
--      * committees: draw_seed / draw_commitment / draw_scheme can only ever be
--        written from inside perform_committee_draw; once a ballot draw exists,
--        drawn_at and payout_method are frozen.
--      * committee_members: once the parent committee carries a draw seed, slot
--        becomes immutable and no member may be inserted or deleted.
--    Without (2), an organiser could simply INSERT a committee that already
--    carries a brute-forced seed, or re-order the slots afterwards. Fixing the
--    RPC alone would have moved the hole, not closed it.
--
-- ── Single-phase, and why that is the right bar here ────────────────────────
--
-- The audit's suggested fix was a two-RPC commit-then-reveal. Commit-reveal
-- exists to constrain an UNTRUSTED source of randomness. Here the randomness is
-- generated by Postgres inside the same transaction that consumes it: the
-- organiser has no pre-image, no retry, and no write path to the seed. A
-- pre-draw commitment would add a round trip and a new "committed but never
-- revealed" state to reason about, and would buy nothing — the organiser cannot
-- influence a seed they never touch. Nothing in the app publishes a commitment
-- to witnesses before the draw either (the witness panel only appears after
-- drawn_at), so there is no pre-draw audience for a commitment to bind.
--
-- draw_commitment is therefore a SEAL, not a commitment: sha256(seed), written
-- with the seed, so any later edit of the seed is detectable. It is what
-- src/components/CommitteeVerifyDraw.tsx already displays.
--
-- ── Determinism scheme: "sha256-rank-v1" ────────────────────────────────────
--
--   rank(id) = encode(digest(seed || ':' || member_id, 'sha256'), 'hex')
--   order    = member ids sorted by rank ASC, ties broken by member_id ASC,
--              both compared byte-wise (collate "C" == JavaScript string `<`
--              over lowercase hex).
--   slot(id) = position in that order, 1-based.
--
-- This REPLACES the previous xmur3 + mulberry32 Fisher-Yates shuffle. That PRNG
-- could not be ported to plpgsql without hand-rolling 32-bit Math.imul wrap
-- semantics, and a server draw the client cannot reproduce byte-for-byte would
-- be worse than no server draw at all. src/lib/committeeDraw.ts was changed to
-- match, and keeps the legacy shuffle for VERIFY-ONLY so pre-fix rows are not
-- painted as tampered. Rows drawn before this migration are backfilled with
-- draw_scheme = 'mulberry32-shuffle-v0' — verification query 5.6 lists them.
--
-- ── FIXED CROSS-CHECK VECTOR (mirrors src/lib/committeeDraw.test.ts) ────────
--
--   seed       = '00112233445566778899aabbccddeeff'
--   member ids = m1, m2, m3, m4, m5
--   ranks:
--     m1 -> 51e0bdc994f0427918337c264c882c5f8ee0744dc748f9fe21551065a53adb6a
--     m2 -> 90d21fef9a44c2cd2618b4d53b8d9c229221d004f86d5074a015c32d540b2825
--     m3 -> bd5fddabdfbcf0149db3b82b907180b6af15a644affcb4aa2f53190ff1c8e667
--     m4 -> 059f50d5e2c6af646c6a7f0a8b9e449fcec8d1d73bfdc99c003470cbe608a524
--     m5 -> c9cf26d8917790e30295caae45412598ed5b84a93e5d1baaf6accd499d764ed5
--   order      = {m4, m1, m2, m3, m5}   (so m4 gets slot 1, m5 slot 5)
--   commitment = sha256(seed)
--              = 5947d7c33d783f94b3b4c1a96ebc8991ed28f1b069b71e03376cba8caa98a720
--
--   Verification query 5.1 below re-derives this in SQL. If it ever stops
--   matching, the server draw and the client recompute have diverged and every
--   witness verification is a coin flip — treat it as a launch blocker.
--
-- ── App modes ───────────────────────────────────────────────────────────────
-- Kameti is mode-agnostic: it is a NO-CUSTODY tracker. Neither full_tracker nor
-- splits_only creates accounts, transactions or balance deltas from a draw —
-- the draw only assigns committee_members.slot. Nothing here touches money, so
-- there is no per-mode artifact divergence to trace (contrast tasks/lessons.md
-- on repayments). Both modes reach the same RPC through the same store action.

-- ═══════════════════════════════════════════════════════════
-- 1. Schema
-- ═══════════════════════════════════════════════════════════

-- digest() / gen_random_bytes() live in pgcrypto. Supabase ships it; this is a
-- no-op if already installed (in whichever schema it was installed into).
create extension if not exists pgcrypto;

alter table public.committees add column if not exists draw_scheme text;

comment on column public.committees.draw_scheme is
  'Which deterministic ordering produced the stored slots. sha256-rank-v1 = server draw (perform_committee_draw). mulberry32-shuffle-v0 = legacy pre-audit client draw, verify-only, NOT server-guaranteed.';

-- Provenance for rows drawn before this migration. Only stamps rows that
-- actually carry a seed, and never overwrites an existing value. Wrapped in the
-- draw-context flag so that on a RE-RUN (when section 3's trigger already
-- exists) this write isn't rejected as a client tampering attempt. The DO block
-- is its own transaction, so the flag cannot outlive it.
do $$
begin
  perform set_config('hisaab.committee_draw', 'on', true);
  update public.committees
     set draw_scheme = 'mulberry32-shuffle-v0'
   where draw_seed is not null
     and draw_scheme is null;
  perform set_config('hisaab.committee_draw', 'off', true);
end $$;

-- ═══════════════════════════════════════════════════════════
-- 2. The server draw
-- ═══════════════════════════════════════════════════════════

create or replace function public.perform_committee_draw(p_committee_id text)
returns json
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_uid        uuid := auth.uid();
  v            public.committees;
  v_members    int;
  v_slotted    int;
  v_seed       text;
  v_commitment text;
  v_drawn_at   timestamptz;
  v_order      text[];
begin
  if v_uid is null then
    raise exception 'perform_committee_draw: NOT_AUTHENTICATED';
  end if;

  -- FOR UPDATE serialises the double-tap: the second call blocks here, then
  -- sees the first call's drawn_at and bails with ALREADY_DRAWN.
  select * into v from public.committees where id = p_committee_id for update;
  if not found then
    raise exception 'perform_committee_draw: NOT_FOUND';
  end if;

  if v.user_id <> v_uid then
    raise exception 'perform_committee_draw: NOT_ORGANISER';
  end if;

  if v.status <> 'active' then
    raise exception 'perform_committee_draw: NOT_ACTIVE';
  end if;

  -- The drawn-guard. Any one of these three means an order already exists and
  -- members may have seen it; re-rolling is exactly the abuse M10 describes.
  select count(*), count(*) filter (where slot is not null)
    into v_members, v_slotted
    from public.committee_members
   where committee_id = v.id;

  if v.drawn_at is not null or v.draw_seed is not null or v_slotted > 0 then
    raise exception 'perform_committee_draw: ALREADY_DRAWN';
  end if;

  if v_members < 2 then
    raise exception 'perform_committee_draw: TOO_FEW_MEMBERS';
  end if;

  -- Server entropy. 16 bytes -> 32 lowercase hex chars, matching the format the
  -- client already renders. The organiser has no input to and no pre-image of
  -- this value; it is consumed in the same statement block that creates it.
  v_seed       := encode(gen_random_bytes(16), 'hex');
  v_commitment := encode(digest(v_seed, 'sha256'), 'hex');
  v_drawn_at   := now();

  -- Let the immutability triggers below know these writes come from here.
  -- set_config(..., true) is transaction-local, so it cannot leak to a later
  -- statement on the same pooled connection.
  perform set_config('hisaab.committee_draw', 'on', true);

  -- sha256-rank-v1. collate "C" pins byte-order comparison so the ordering
  -- cannot drift with the database's collation.
  select array_agg(member_id order by rank_hex collate "C", member_id collate "C")
    into v_order
    from (
      select m.id::text as member_id,
             encode(digest(v_seed || ':' || m.id::text, 'sha256'), 'hex') as rank_hex
        from public.committee_members m
       where m.committee_id = v.id
    ) ranked;

  update public.committee_members m
     set slot = pos.ord
    from unnest(v_order) with ordinality as pos(member_id, ord)
   where m.committee_id = v.id
     and m.id = pos.member_id;

  update public.committees
     set payout_method   = 'ballot',
         drawn_at        = v_drawn_at,
         draw_seed       = v_seed,
         draw_commitment = v_commitment,
         draw_scheme     = 'sha256-rank-v1',
         updated_at      = now()
   where id = v.id;

  perform set_config('hisaab.committee_draw', 'off', true);

  return json_build_object(
    'status',         'ok',
    'committeeId',    v.id,
    'payoutMethod',   'ballot',
    'drawnAt',        v_drawn_at,
    'drawSeed',       v_seed,
    'drawCommitment', v_commitment,
    'drawScheme',     'sha256-rank-v1',
    'order',          to_json(v_order)
  );
end $$;

revoke all on function public.perform_committee_draw(text) from public, anon;
grant execute on function public.perform_committee_draw(text) to authenticated;

comment on function public.perform_committee_draw(text) is
  'Audit 2026-09 C10/M10. Organiser-only, once-only server ballot draw. Seed is server-generated; ordering is sha256-rank-v1. Second call raises ALREADY_DRAWN.';

-- ═══════════════════════════════════════════════════════════
-- 3. Make the draw append-only against raw PostgREST writes
-- ═══════════════════════════════════════════════════════════

create or replace function public.tg_committees_draw_immutable()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_in_draw boolean := coalesce(current_setting('hisaab.committee_draw', true), 'off') = 'on';
begin
  if v_in_draw then
    return new;
  end if;

  if tg_op = 'INSERT' then
    -- A client that could insert its own seed could brute-force a seed matching
    -- a hand-picked order (~N! hashes) and every verification would pass.
    if new.draw_seed is not null or new.draw_commitment is not null or new.draw_scheme is not null then
      raise exception 'committees: DRAW_FIELDS_ARE_SERVER_ONLY — use perform_committee_draw()';
    end if;
    return new;
  end if;

  if new.draw_seed is distinct from old.draw_seed
     or new.draw_commitment is distinct from old.draw_commitment
     or new.draw_scheme is distinct from old.draw_scheme then
    raise exception 'committees: DRAW_FIELDS_ARE_SERVER_ONLY — use perform_committee_draw()';
  end if;

  -- Once a ballot draw exists the outcome is frozen: no re-dating it, and no
  -- flipping to 'fixed' to escape the member-slot lock in section 3b.
  if old.draw_seed is not null then
    if new.drawn_at is distinct from old.drawn_at then
      raise exception 'committees: DRAW_LOCKED — drawn_at is immutable after a draw';
    end if;
    if new.payout_method is distinct from old.payout_method then
      raise exception 'committees: DRAW_LOCKED — payout_method is immutable after a draw';
    end if;
  end if;

  return new;
end $$;

drop trigger if exists trg_committees_draw_immutable on public.committees;
create trigger trg_committees_draw_immutable
  before insert or update on public.committees
  for each row execute function public.tg_committees_draw_immutable();

-- 3b. Slots and membership freeze once a ballot draw exists — otherwise the
--     organiser keeps the honest seed and simply rewrites the slots. (That is
--     detectable by CommitteeVerifyDraw, but "detectable" is a weaker promise
--     than "impossible", and the witness page is what non-app relatives see.)
--
--     DELETE is deliberately NOT blocked. Deleting a committee cascades into
--     committee_members, and a BEFORE DELETE guard here would make
--     committeesDb.delete() fail on every drawn kameti — a worse bug than the
--     one it closes. Removing a member after a draw still breaks verification
--     loudly (the member list no longer reproduces the stored order), so it is
--     detectable rather than silent.
create or replace function public.tg_committee_members_draw_locked()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_drawn boolean;
begin
  if coalesce(current_setting('hisaab.committee_draw', true), 'off') = 'on' then
    return new;
  end if;

  select (c.draw_seed is not null) into v_drawn
    from public.committees c where c.id = new.committee_id;

  -- Not drawn (or parent already gone) → nothing to protect.
  if v_drawn is not true then
    return new;
  end if;

  if tg_op = 'INSERT' then
    raise exception 'committee_members: DRAW_LOCKED — cannot add a member after the ballot draw';
  end if;

  if new.slot is distinct from old.slot then
    raise exception 'committee_members: DRAW_LOCKED — slot is immutable after the ballot draw';
  end if;

  if new.committee_id is distinct from old.committee_id then
    raise exception 'committee_members: DRAW_LOCKED — a drawn member cannot be moved between committees';
  end if;

  return new;
end $$;

drop trigger if exists trg_committee_members_draw_locked on public.committee_members;
create trigger trg_committee_members_draw_locked
  before insert or update on public.committee_members
  for each row execute function public.tg_committee_members_draw_locked();

-- ═══════════════════════════════════════════════════════════
-- 4. Witness payload carries the scheme
-- ═══════════════════════════════════════════════════════════
-- Unchanged from phase2 except for the added 'drawScheme' key, so a witness can
-- tell a server draw from a legacy client draw without an account. Redefined
-- in full because create or replace cannot patch a function body.

create or replace function public.get_committee_witness(p_token text)
returns json
language plpgsql security definer set search_path = public as $$
declare
  v public.committees;
  result json;
begin
  if p_token is null or length(p_token) < 8 then
    return null;
  end if;
  select * into v from public.committees where share_token = p_token;
  if not found then
    return null;
  end if;

  select json_build_object(
    'committee', json_build_object(
      'id', v.id, 'name', v.name, 'currency', v.currency,
      'contributionAmount', v.contribution_amount, 'memberCount', v.member_count,
      'cadence', v.cadence, 'totalRounds', v.total_rounds, 'startDate', v.start_date,
      'payoutMethod', v.payout_method, 'status', v.status, 'drawnAt', v.drawn_at,
      'drawSeed', v.draw_seed, 'drawCommitment', v.draw_commitment,
      'drawScheme', v.draw_scheme, 'createdAt', v.created_at
    ),
    'members', coalesce((
      select json_agg(json_build_object(
        'id', m.id, 'name', m.name, 'slot', m.slot, 'isOrganizer', m.is_organizer,
        'payoutReceivedAt', m.payout_received_at, 'exitedAt', m.exited_at
      ) order by m.slot nulls last, m.created_at)
      from public.committee_members m where m.committee_id = v.id
    ), '[]'::json),
    'payments', coalesce((
      select json_agg(json_build_object('memberId', p.member_id, 'round', p.round))
      from public.committee_payments p where p.committee_id = v.id
    ), '[]'::json)
  ) into result;

  return result;
end $$;

grant execute on function public.get_committee_witness(text) to anon, authenticated;

-- ═══════════════════════════════════════════════════════════
-- 5. VERIFICATION — run after applying
-- ═══════════════════════════════════════════════════════════
-- (If digest()/gen_random_bytes() are unqualified-unresolvable in your Studio
--  session, prefix them with the schema pgcrypto was installed into, usually
--  `extensions.`.)

-- 5.1 THE CROSS-CHECK. Must reproduce the vector in this file's header and in
--     src/lib/committeeDraw.test.ts. Expect: {m4,m1,m2,m3,m5}
select array_agg(member_id order by rank_hex collate "C", member_id collate "C") as sql_order
  from (
    select m.id::text as member_id,
           encode(digest('00112233445566778899aabbccddeeff' || ':' || m.id, 'sha256'), 'hex') as rank_hex
      from (values ('m1'),('m2'),('m3'),('m4'),('m5')) as m(id)
  ) ranked;

-- 5.2 The seal for the same vector.
--     Expect: 5947d7c33d783f94b3b4c1a96ebc8991ed28f1b069b71e03376cba8caa98a720
select encode(digest('00112233445566778899aabbccddeeff', 'sha256'), 'hex') as commitment;

-- 5.3 The RPC exists, is SECURITY DEFINER, and anon cannot call it.
select p.proname, p.prosecdef,
       has_function_privilege('authenticated', p.oid, 'EXECUTE') as auth_can,
       has_function_privilege('anon',          p.oid, 'EXECUTE') as anon_can
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
 where n.nspname = 'public' and p.proname = 'perform_committee_draw';
-- Expect: one row, prosecdef = t, auth_can = t, anon_can = f

-- 5.4 Both immutability triggers are armed.
select c.relname, t.tgname, t.tgenabled
  from pg_trigger t join pg_class c on c.oid = t.tgrelid
 where t.tgname in ('trg_committees_draw_immutable', 'trg_committee_members_draw_locked');
-- Expect: two rows, tgenabled = 'O' for both

-- 5.5 The scheme column exists.
select column_name, data_type
  from information_schema.columns
 where table_schema = 'public' and table_name = 'committees' and column_name = 'draw_scheme';
-- Expect: one row, text

-- 5.6 Provenance of every existing draw. Anything still on
--     'mulberry32-shuffle-v0' is a PRE-FIX record: its order matches its seed,
--     but the seed came from the organiser's device and carries no server
--     guarantee. Pre-launch these should be test data — delete them (or accept
--     that their fairness is unproven).
select coalesce(draw_scheme, '(none)') as scheme, count(*), min(drawn_at) as oldest
  from public.committees
 where draw_seed is not null
 group by 1;

-- 5.7 No committee carries a seed whose slots were never assigned (would mean a
--     half-applied draw). Expect: 0
select count(*) as seeded_but_unslotted
  from public.committees c
 where c.draw_seed is not null
   and not exists (select 1 from public.committee_members m
                    where m.committee_id = c.id and m.slot is not null);

-- 5.8 Manual QA as a signed-in organiser (do this on a throwaway committee):
--   a. Create a 'ballot' kameti with 4 members, then:
--        select public.perform_committee_draw('<committee id>');
--      -> {"status":"ok", ..., "drawScheme":"sha256-rank-v1", "order":[...]}
--   b. Call it a SECOND time
--      -> ERROR: perform_committee_draw: ALREADY_DRAWN   (slots unchanged)
--   c. As a DIFFERENT signed-in user:
--        select public.perform_committee_draw('<same id>');
--      -> ERROR: perform_committee_draw: NOT_ORGANISER
--   d. Try to rig it by hand (this is the M10 attack, and must now fail):
--        update public.committees set draw_seed = 'deadbeef' where id = '<id>';
--      -> ERROR: committees: DRAW_FIELDS_ARE_SERVER_ONLY
--        update public.committee_members set slot = 1 where id = '<any member>';
--      -> ERROR: committee_members: DRAW_LOCKED
--        insert into public.committees (..., draw_seed, draw_commitment) values (...);
--      -> ERROR: committees: DRAW_FIELDS_ARE_SERVER_ONLY
--   e. Open the witness link and press "Check this draw" -> must say verified.
--      Recompute independently to be sure, e.g.:
--        printf '%s' '<drawSeed>:<member id>' | sha256sum
--      Sorting every member by that hash must reproduce the slot order shown.
